//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace SimpleWordPad.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleWordPad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap Custom_Icon_Design_Mono_General_2_Copy {
            get {
                object obj = ResourceManager.GetObject("Custom-Icon-Design-Mono-General-2-Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Custom_Icon_Design_Mono_General_2_Cut {
            get {
                object obj = ResourceManager.GetObject("Custom-Icon-Design-Mono-General-2-Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        

        internal static System.Drawing.Bitmap Double_J_Design_Ravenna_3d_Save {
            get {
                object obj = ResourceManager.GetObject("Double-J-Design-Ravenna-3d-Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Gakuseisean_Ivista_2_Files_New_File {
            get {
                object obj = ResourceManager.GetObject("Gakuseisean-Ivista-2-Files-New-File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Hopstarter_Soft_Scraps_Document_Preview {
            get {
                object obj = ResourceManager.GetObject("Hopstarter-Soft-Scraps-Document-Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Iconmoon_Viva_Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Iconmoon-Viva-Folder-Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons8_Ios7_Editing_Strikethrough {
            get {
                object obj = ResourceManager.GetObject("Icons8-Ios7-Editing-Strikethrough", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Icons8_Ios7_Editing_Underline {
            get {
                object obj = ResourceManager.GetObject("Icons8-Ios7-Editing-Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Icons8_Windows_8_Editing_Bold {
            get {
                object obj = ResourceManager.GetObject("Icons8-Windows-8-Editing-Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Icons8_Windows_8_Editing_Italic {
            get {
                object obj = ResourceManager.GetObject("Icons8-Windows-8-Editing-Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Icons8_Windows_8_Editing_Paste_Special {
            get {
                object obj = ResourceManager.GetObject("Icons8-Windows-8-Editing-Paste-Special", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Iconshock_Real_Vista_Text_Print {
            get {
                object obj = ResourceManager.GetObject("Iconshock-Real-Vista-Text-Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Iconsmind_Outline_Normal_Text {
            get {
                object obj = ResourceManager.GetObject("Iconsmind-Outline-Normal-Text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Mart_Glaze_Info {
            get {
                object obj = ResourceManager.GetObject("Mart-Glaze-Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Pelfusion_Flat_Folder_Open_Folder {
            get {
                object obj = ResourceManager.GetObject("Pelfusion-Flat-Folder-Open-Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tatice_Cristal_Intense_Dossier_bleu {
            get {
                object obj = ResourceManager.GetObject("Tatice-Cristal-Intense-Dossier-bleu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Toma4025_Rumax_Folder_fonts {
            get {
                object obj = ResourceManager.GetObject("Toma4025-Rumax-Folder-fonts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Trayse101_Photoshop_Filetypes_Colors {
            get {
                object obj = ResourceManager.GetObject("Trayse101-Photoshop-Filetypes-Colors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Visualpharm_Must_Have_Redo {
            get {
                object obj = ResourceManager.GetObject("Visualpharm-Must-Have-Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Visualpharm_Must_Have_Undo {
            get {
                object obj = ResourceManager.GetObject("Visualpharm-Must-Have-Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Wordpad_icon {
            get {
                object obj = ResourceManager.GetObject("Wordpad-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
